### ISSUE TITLE
About the labeling process for the Urban Region Function Recognition (URFR) task.

### ISSUE THREAD

**Issue by SQLai2099** [LwbXc/STBench#1]
Very brilliant work. I am curious about the labeling process for the Urban Region Function Recognition (URFR) task. How do you determine the function of each region in the dataset? By POIs or Yelp comments?

**Comment by LwbXc** [comment]
We obtained the region function labels from this [US government website](https://catalog.data.gov/dataset/zoning-district-9939c). The Comma Separated Values File on this website contains the zoning code for each geometry, such as "HMC-1" and "HU-B1A". Then we converted the zoning codes into corresponding meanings, _e.g._, "Historic Marigny Treme Bywater Commercial District", based on the information on another [website](https://www.zoneomics.com/zoning-maps/louisiana/new-orleans).

**Comment by SQLai2099** [comment]
Thank you for the prompt feedback.
